package com.myhive.backend.ai.llm;

import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.SystemMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.metadata.ChatResponseMetadata;
import org.springframework.ai.chat.metadata.Usage;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.openai.OpenAiChatModel.ResponseFormat;
import org.springframework.ai.openai.OpenAiChatOptions;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Executor;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/** Qwen through Spring AI's OpenAI client. JSON (schema) mode + thinking off so the reply is parseable JSON. */
@Component
@Primary
@Slf4j
public class SpringAiLlmGateway implements LlmGateway {

    private static final int HISTORY_FOR_CHAT = 20;
    private static final double CHAT_TEMPERATURE = 0.7;
    private static final double PLANNER_TEMPERATURE = 0.4;
    /**
     * Turns Qwen's hybrid reasoning off, in both dialects the OpenAI-compatible endpoints understand:
     * DashScope reads the top-level {@code enable_thinking} flag, OpenRouter ignores it and reads
     * {@code reasoning.enabled} instead (with it ignored, the model spends the whole token budget on a
     * reasoning block and returns a null {@code content}). Each provider ignores the other's key, so both
     * are always sent. Without either, JSON mode does not suppress the &lt;think&gt; block.
     */
    private static final Map<String, Object> THINKING_OFF = Map.of(
            "enable_thinking", false,
            "reasoning", Map.of("enabled", false));

    private final ChatModel chatModel;
    private final PromptRenderer renderer;
    private final LlmOutputParser parser;
    private final AiProperties props;
    private final Executor llmCallExecutor;

    /** Written out rather than generated by Lombok so the executor can carry its qualifier. */
    public SpringAiLlmGateway(ChatModel chatModel, PromptRenderer renderer, LlmOutputParser parser,
                              AiProperties props, @Qualifier("llmCallExecutor") Executor llmCallExecutor) {
        this.chatModel = chatModel;
        this.renderer = renderer;
        this.parser = parser;
        this.props = props;
        this.llmCallExecutor = llmCallExecutor;
    }

    @Override
    public ChatTurnResult chatTurn(ChatTurnRequest request) {
        List<Message> messages = new ArrayList<>();
        messages.add(new SystemMessage(renderer.chatSystem(request)));
        List<ChatMessage> history = request.history();
        int from = Math.max(0, history.size() - HISTORY_FOR_CHAT);
        for (int i = from; i < history.size(); i++) {
            ChatMessage message = history.get(i);
            boolean last = i == history.size() - 1;
            if (ChatMessage.USER.equals(message.role())) {
                messages.add(new UserMessage(last ? renderer.wrapUser(message.content()) : message.content()));
            } else {
                messages.add(new AssistantMessage(message.content()));
            }
        }
        Timed timed = call(messages, props.getChatModel(), CHAT_TEMPERATURE, props.getChatTimeout());
        return parser.parseChatTurn(timed.text()).withUsage(timed.usage());
    }

    @Override
    public PlanDraftResult composePlan(PlanRequest request) {
        List<Message> messages = List.of(
                new SystemMessage(renderer.plannerSystem(request)),
                new UserMessage(renderer.plannerUser(request)));
        Timed timed = call(messages, props.getPlannerModel(), PLANNER_TEMPERATURE, props.getPlannerTimeout(),
                ResponseSchemas.plan(request.catalog()));
        return new PlanDraftResult(parser.parsePlan(timed.text(), request.catalog()), timed.usage());
    }

    @Override
    public PlanDraftResult repairPlan(RepairRequest request) {
        List<Message> messages = List.of(
                new SystemMessage(renderer.plannerSystem(request.original())),
                new UserMessage(renderer.plannerUser(request.original())),
                new UserMessage(renderer.repairUser(request)));
        Timed timed = call(messages, props.getPlannerModel(), PLANNER_TEMPERATURE, props.getPlannerTimeout(),
                ResponseSchemas.plan(request.original().catalog()));
        return new PlanDraftResult(parser.parsePlan(timed.text(), request.original().catalog()), timed.usage());
    }

    @Override
    public TextRefreshResult refreshTexts(TextRefreshRequest request) {
        List<Message> messages = List.of(
                new SystemMessage(renderer.textRefreshSystem(request)),
                new UserMessage(renderer.textRefreshUser(request)));
        Timed timed = call(messages, props.getChatModel(), CHAT_TEMPERATURE, props.getChatTimeout());
        return new TextRefreshResult(parser.parseTextRefresh(timed.text()), timed.usage());
    }

    /** Copy is the chat model's job; it gets its own budget because three packages of it outrun a chat turn. */
    @Override
    public PlanTextsResult writeTexts(PlanTextsRequest request) {
        List<Message> messages = List.of(
                new SystemMessage(renderer.planTextsSystem(request)),
                new UserMessage(renderer.planTextsUser(request)));
        Timed timed = call(messages, props.getChatModel(), CHAT_TEMPERATURE, props.getTextsTimeout(),
                ResponseSchemas.planTexts());
        return new PlanTextsResult(parser.parsePackageTexts(timed.text(), ActivityAliases.toId(request.catalog())),
                timed.usage());
    }

    private record Timed(String text, LlmUsage usage) {
    }

    private Timed call(List<Message> messages, String model, double temperature, Duration timeout) {
        return call(messages, model, temperature, timeout, null);
    }

    /** {@code schema} null means plain JSON mode; see {@link #options}. */
    private Timed call(List<Message> messages, String model, double temperature, Duration timeout, String schema) {
        Prompt prompt = new Prompt(messages, options(model, temperature, schema));
        long started = System.nanoTime();
        try {
            ChatResponse response = CompletableFuture.supplyAsync(() -> chatModel.call(prompt), llmCallExecutor)
                    .get(timeout.toMillis(), TimeUnit.MILLISECONDS);
            if (response == null || response.getResult() == null) {
                throw unparseable(model, started, "model returned no response");
            }
            long latency = elapsedMs(started);
            LlmUsage llmUsage = usageOf(response, model, latency);
            String text = response.getResult().getOutput().getText();
            if (text == null) {
                throw unparseable(model, started, "model returned no text");
            }
            log.info("llm call model={} latencyMs={} promptTokens={} completionTokens={}", model, latency,
                    llmUsage.promptTokens(), llmUsage.completionTokens());
            return new Timed(text, llmUsage);
        } catch (RejectedExecutionException e) {
            throw unavailable(model, started, "model call rejected: executor saturated", e);
        } catch (TimeoutException e) {
            throw unavailable(model, started, "model call timed out after " + timeout, e);
        } catch (ExecutionException e) {
            Throwable cause = e.getCause() == null ? e : e.getCause();
            throw unavailable(model, started, "model call failed: " + cause.getMessage(), cause);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw unavailable(model, started, "model call interrupted", e);
        }
    }

    /**
     * Per-call options: the model and temperature this leg needs, the response format, and Qwen's thinking
     * flag. A leg with a schema gets strict JSON-schema mode (Model Studio supports it for the Qwen3.7-Plus
     * and Qwen3.8-Max series) unless {@code app.ai.strict-schema} is off; everything else gets JSON mode.
     */
    private OpenAiChatOptions options(String model, double temperature, String schema) {
        ResponseFormat format = schema != null && props.isStrictSchema()
                ? ResponseFormat.builder().type(ResponseFormat.Type.JSON_SCHEMA).jsonSchema(schema).strict(true).build()
                : ResponseFormat.builder().type(ResponseFormat.Type.JSON_OBJECT).build();
        return OpenAiChatOptions.builder()
                .model(model)
                .temperature(temperature)
                .responseFormat(format)
                .extraBody(THINKING_OFF)
                .build();
    }

    /** One warn line per failed call. Never logs prompts or replies -- only the model and the shape of the failure. */
    private LlmUnavailableException unavailable(String model, long startedNanos, String message, Throwable cause) {
        log.warn("llm call failed model={} elapsedMs={} cause={}", model, elapsedMs(startedNanos),
                cause.getClass().getSimpleName());
        return new LlmUnavailableException(message, cause);
    }

    private LlmOutputException unparseable(String model, long startedNanos, String message) {
        log.warn("llm call failed model={} elapsedMs={} cause={}", model, elapsedMs(startedNanos),
                LlmOutputException.class.getSimpleName());
        return new LlmOutputException(message);
    }

    private static long elapsedMs(long startedNanos) {
        return (System.nanoTime() - startedNanos) / 1_000_000L;
    }

    private static LlmUsage usageOf(ChatResponse response, String model, long latencyMs) {
        ChatResponseMetadata metadata = response.getMetadata();
        Usage usage = metadata == null ? null : metadata.getUsage();
        return new LlmUsage(model,
                usage == null ? null : usage.getPromptTokens(),
                usage == null ? null : usage.getCompletionTokens(), latencyMs);
    }
}
