#!/usr/bin/env node
// Builds prod-migration-translations-<locale>.sql from content/translations-<locale>/*.json.
//
//   node scripts/translations-to-sql.mjs de
//
// Every JSON file holds any of the sections destinations / categories /
// activities / packages / blog (keyed by slug) and quizQuestions / quizAnswers
// (keyed by the English prompt / label — quiz rows are recreated with new ids
// on every admin save, the text is the stable handle); files are merged (later
// files win on key collisions, which are reported). The SQL merges the locale
// into the row's translations column without touching other locales, and only
// touches rows whose key exists — nothing is inserted. Run the output against
// the prod database (IDEA datasource or psql) and let the hourly ISR
// revalidate pick it up, or redeploy the frontend for an instant refresh.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const locale = process.argv[2];
if (!/^[a-z]{2}$/.test(locale ?? '')) {
  console.error('usage: node scripts/translations-to-sql.mjs <locale>   e.g. de');
  process.exit(1);
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'content', `translations-${locale}`);
const outFile = path.join(root, `prod-migration-translations-${locale}.sql`);

// section -> { table, column the JSON keys match on }
const TABLES = {
  destinations: { table: 'destinations', key: 'slug' },
  categories: { table: 'categories', key: 'slug' },
  activities: { table: 'activities', key: 'slug' },
  packages: { table: 'packages', key: 'slug' },
  blog: { table: 'blog_posts', key: 'slug' },
  quizQuestions: { table: 'quiz_questions', key: 'prompt' },
  quizAnswers: { table: 'quiz_answers', key: 'label' },
};

const merged = Object.fromEntries(Object.keys(TABLES).map((k) => [k, new Map()]));
const files = readdirSync(srcDir).filter((f) => f.endsWith('.json')).sort();
for (const file of files) {
  const data = JSON.parse(readFileSync(path.join(srcDir, file), 'utf8'));
  for (const [section, rows] of Object.entries(data)) {
    if (!(section in TABLES)) {
      console.warn(`${file}: unknown section "${section}" ignored`);
      continue;
    }
    for (const [slug, fields] of Object.entries(rows)) {
      if (merged[section].has(slug)) {
        console.warn(`${file}: ${section}/${slug} overrides an earlier definition`);
      }
      merged[section].set(slug, fields);
    }
  }
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const lines = [
  `-- Generated by scripts/translations-to-sql.mjs from content/translations-${locale}/ — do not edit by hand.`,
  `-- Merges the "${locale}" locale into each row's translations JSON (other locales are kept);`,
  `-- rows are matched by slug (quiz rows by their English text), nothing is inserted. Safe to re-run.`,
  'BEGIN;',
];
let total = 0;
for (const [section, { table, key }] of Object.entries(TABLES)) {
  const rows = merged[section];
  if (rows.size === 0) continue;
  lines.push('', `-- ${section}: ${rows.size} rows`);
  for (const [id, fields] of rows) {
    const patch = JSON.stringify({ [locale]: fields });
    lines.push(
      `UPDATE ${table} SET translations = (COALESCE(translations::jsonb, '{}'::jsonb) || ${q(patch)}::jsonb)::text WHERE ${key} = ${q(id)};`
    );
    total++;
  }
}
lines.push('', 'COMMIT;', '');

writeFileSync(outFile, lines.join('\n'));
console.log(`${outFile}: ${total} updates from ${files.length} file(s)`);
for (const [section, rows] of Object.entries(merged)) {
  if (rows.size) console.log(`  ${section}: ${rows.size}`);
}
