package com.myhive.backend.ai.plan;

public enum ViolationCode {
    MISSING_TIER, WRONG_DAY_COUNT, UNKNOWN_ACTIVITY, DUPLICATE_ACTIVITY, DAY_OVER_MINUTES, DAY_OVER_ITEMS,
    SLOT_TAKEN, SLOT_OUTSIDE_WINDOW, EMPTY_DAY, EMPTY_PACKAGE, TIER_ORDER, TIER_NOT_DISTINCT, TEXT_TOO_LONG,
    INVALID_OUTPUT
}
